== The Android ORM Project

Having worked with JPA and Hibernate for years, I was a bit, um, "surprised" by the design of Android's "ContentValues" and "ContentProvider" wherein everything is reduced to mush, or at least hash, before it can be processed. So we undertook this little study.

The main project is in CommonCode, which provides JPA-annotated entities and a
"Signup" name-and-address form. When you submit the form, it passes the Person
object on to an ORM-specific SavingActivity, which is expected to do the technology-specific
"save the Person to sqlite" action, and display "success". 

=== TO BUILD A NEW DEMO:

The Main activity's class name must be listed in your AndroidManifest,
and the taret "save and display" must be listed in a Java Properties
file in src/. See TemplateReceiver for example. In more detail:

# Clone this entire project if you didn't already.
# copy the entire TemplateReceiver project to a new project, named after
   your technology (use the names below if implementing one of these?).
# Change the package name from "templatereceiver" to your ORM's name (lower case)
# Make the corresponding change in androidorm.properties
# Add your technology's JAR files into libs/
# Write the "saving" code at the XXX in SavingActivity.
   Note that for threading reasons, everything from the XXX to the end of the method
   should be done in a background thread!

Please DO NOT:

# Switch your build to Maven, Gradle, etc., unless you have a really good reason to;
   (we want them all to work and play the same way, so try to stick w/ the Eclipse build).
# Go changing any other config files; Android build is kinda sensitive to changes,
and we have it working such that TemplateReceiver's main activity is coming from the
library project, it passes control to SavingActivity, and it "just works" as it stands.
# Tart up the UI in SavingActivity; it's just a POC, don't waste your time on frills.

When it works, send me a pull request!

=== Technologies

.List of Android ORM technologies (to be) tried
[options="header"]
|===========
| Technology         | URL  | Type | JPA Annot? | Tech  | Notes
| ------------------:|------|:-------:|-------|------|-----|
| AndroidRecord      | http://www.activeandroid.com/ | Active Record | ?| |   |
| Batoo JPA          | | JPA with Batoo Provider | Y | HSQL database | ?|
| greenDAO           | http://greendao-orm.com/ | ? | ? | ?|
| Gwenn SQLite       | https://github.com/gwenn/sqlite-dialect/ | Hibernate dialect for SQLite | N/A |
| Hibernate          | http://hibernate.org | ORM | Y | with Gwenn SQLite-dialect | 
| Jpa-hibernate      | n/a | ORM | Y | JPA with Hibernate and Gwenn | 
| ORMLite            | ormlite.com | ORM | Y | Supports JDBC, Android | custom | 
| Sugar ORM          | http://satyan.github.io/sugar/ | Active Record | ? | 
| Xerial JDBC-Driver | http://code.google.com/p/xerial/ | JDBC-SQLite| n/a | n/a |
|===========
=== WHO

This project was entirely funded by the Centre for Global eHealth Innovation at the
University Health Network, Toronto. http://ehealthinnovation.org.

The original project setup (CommonCode and TemplateReceiver) was done by Ian Darwin
(http://ehealthinnovation.org/people/ian-darwin/).

Technology-specific projects were contributed by ...
